<%@ Page Language="C#" MasterPageFile="~/Masters/Internal.master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
                
    
<div class="blueUnderlinedTitle">Systems</div>

<p style="margin-bottom:20px;"><strong>RISK OF LOSS IN FUTURES TRADING </strong><br />
  THE RISK  OF LOSS IN TRADING COMMODITY FUTURES CONTRACTS CAN BE SUBSTANTIAL. YOU SHOULD  THEREFORE CAREFULLY CONSIDER WHETHER SUCH TRADING IS SUITABLE IN LIGHT OF YOUR  FINANCIAL CONDITION. IN CONSIDERING WHETHER TO TRADE OR TO AUTHORIZE SOMEONE  ELSE TO TRADE FOR YOU, YOU SHOULD BE AWARE OF THE FOLLOWING: YOU MAY SUSTAIN A  TOTAL LOSS OF THE INITIAL MARGIN FUNDS AND ANY ADDITIONAL FUNDS THAT YOU  DEPOSIT WITH YOUR BROKER TO ESTABLISH OR MAINTAIN YOUR POSITION. IF THE MARKET  MOVES AGAINST YOUR POSITION, YOU MAY BE CALLED UPON BY YOUR BROKER TO DEPOSIT A  SUBSTANTIAL AMOUNT OF ADDITIONAL MARGIN FUNDS, ON SHORT NOTICE, IN ORDER TO  MAINTAIN YOUR POSITION. IF YOU DO NOT PROVIDE THE REQUIRED FUNDS WITHIN THE  PRESCRIBED TIME, YOUR POSITION MAY BE LIQUIDATED AT A LOSS, AND YOU WILL BE  LIABLE FOR ANY RESULTING DEFICIT IN YOUR ACCOUNT. UNDER CERTAIN MARKET  CONDITIONS, YOU MAY FIND IT DIFFICULT OR IMPOSSIBLE TO LIQUIDATE A POSITION. THIS  CAN OCCUR, FOR EXAMPLE, WHEN THE MARKET MAKES A &quot;LIMIT MOVE&quot;. THE  PLACEMENT OF CONTINGENT ORDERS, SUCH AS A &quot;STOP LOSS&quot; OR &quot;STOP  LIMIT&quot; ORDER, WILL NOT NECESSARILY LIMIT YOUR LOSSES TO THE INTENDED  AMOUNTS, SINCE MARKET CONDITIONS MAY MAKE IT IMPOSSIBLE TO EXECUTE SUCH ORDERS.  A &quot;SPREAD&quot; POSITION MAY NOT BE LESS RISKY THAN A SIMPLE  &quot;LONG&quot; OR &quot;SHORT&quot; POSITION. THE HIGH DEGREE OF LEVERAGE  THAT IS OFTEN OBTAINABLE IN FUTURES TRADING BECAUSE OF THE SMALL MARGIN  REQUIREMENT CAN WORK AGAINST YOU AS WELL AS FOR YOU. THE USE OF LEVERAGE CAN  LEAD TO LARGE LOSSES AS WELL AS GAINS. THIS BRIEF STATEMENT CANNOT, OF COURSE,  DISCLOSE ALL THE RISKS AND OTHER SIGNIFICANT ASPECTS OF THE COMMODITY MARKETS.  YOU SHOULD THEREFORE CAREFULLY STUDY FUTURES TRADING BEFORE YOU TRADE. <br />
  <br />
  <strong>HYPOTHETICAL PERFORMANCE RESULTS </strong><br />
  HYPOTHETICAL  PERFORMANCE RESULTS HAVE MANY INHERENT LIMITATIONS, SOME OF WHICH ARE DESCRIBED  BELOW. NO REPRESENTATION IS BEING MADE THAT ANY COMMODITY TRADING ACCOUNT WILL  OR IS LIKELY TO ACHIEVE PROFITS OR LOSSES SIMILAR TO THOSE SHOWN. IN FACT,  THERE ARE FREQUENTLY SHARP DIFFERENCES BETWEEN HYPOTHETICAL COMMODITY TRADING  PERFORMANCE RESULTS AND THE ACTUAL RESULTS SUBSEQUENTLY ACHIEVED BY ANY  PARTICULAR COMMODITY TRADING PROGRAM. ONE OF THE LIMITATIONS OF HYPOTHETICAL  COMMODITY TRADING PERFORMANCE RESULTS IS THAT THEY ARE GENERALLY PREPARED WITH  THE BENEFIT OF HINDSIGHT. IN ADDITION, HYPOTHETICAL COMMODITY TRADING DOES NOT  INVOLVE FINANCIAL RISK, AND NO HYPOTHETICAL COMMODITY TRADING RECORD CAN  COMPLETELY ACCOUNT FOR THE IMPACT OF FINANCIAL RISK IN ACTUAL COMMODITY  TRADING. FOR EXAMPLE, THE ABILITY TO WITHSTAND LOSSES OR TO ADHERE TO A  PARTICULAR COMMODITY TRADING PROGRAM IN SPITE OF TRADING LOSSES ARE MATERIAL  POINTS WHICH CAN ALSO ADVERSELY AFFECT ACTUAL COMMODITY TRADING RESULTS. THERE  ARE NUMEROUS OTHER FACTORS RELATED TO THE COMMODITY MARKETS IN GENERAL OR TO  THE IMPLEMENTATION OF ANY SPECIFIC COMMODITY TRADING PROGRAM WHICH CAN NOT BE  FULLY ACCOUNTED FOR IN THE PREPARATION OF HYPOTHETICAL COMMODITY TRADING PERFORMANCE  RESULTS, AND ALL OF WHICH CAN ADVERSELY AFFECT ACTUAL COMMODITY TRADING  RESULTS. <br />
  <br />
  <strong>ADDITIONAL GLOBEX TRADING  SOLUTIONS DISCLOSURES </strong><br />
  All  material provided by Globex Trading Solutions is believed to be reliable.  However, due to the number of sources from which we obtain information, and the  inherent risks of distribution, there may be omissions or inaccuracies in such  information and services. Globex Trading Solutions its owners, employees, and  contributors take every reasonable step to ensure the integrity of the data.  However, Globex Trading Solutions, its owners, employees, and contributors,  cannot and will not warrant the accuracy, completeness, or fitness for a  particular purpose of the information contained in our products or services.  Recommendations and opinions contained in our products and services reflect  judgment, as applicable, of Globex&nbsp; Trading Solutions as of the date  hereof, are subject to change, and are based upon certain assumptions that  could yield different results. You are cautioned there is no universally  accepted method for analyzing financial instruments, including futures.  Further, there is no guarantee as to the liquidity of the instruments involved  in its analysis. <br />
  Neither  the information nor the recommendations and opinions expressed herein  constitute an offer to buy or sell any financial contracts, security, future  contract, or derivative instrument. As a matter of policy, Globex Trading  Solutions does not give tax, accounting, regulatory, or legal advice to  clients. A client should therefore consult their own advisor regarding the tax,  accounting, regulatory, or legal implications of the recommended strategies  before any transactions with your account. <br />
  Prior to  opening an account the undersigned should contact the National Futures  Association to further research the risks involved with futures trading. The  National Futures Association can be contacted at: <br />
  NationalFuturesAssociation <br />
  200WestMadisonStreet,Suite600 <br />
  Chicago,IL60606 <br />
  Phone:1.800.621.3570<br />
  Email: <a href="mailto:www.nfa.futures.org">www.nfa.futures.org</a> <br />
  This does  not imply that the National Futures Association endorses this product or any  products of Globex Trading Solutions. This is not an offer to buy or sell  futures contracts or financial instruments of any kind. Notwithstanding any  communications between Globex Trading Solutions and its customers and prospects  to the contrary, receipt or use of any material provided by Globex Trading  Solutions, at any time distributed via any method, represents acknowledgement  by such persons of this disclaimer and agreement with its terms and conditions. <br />
  <br />
  <strong>COMMISSION ADVISORY </strong><br />
  Beware of  Websites Selling Commodity Trading Systems that Guarantee High Profits with  Minimal Risks The United States Commodity Futures Trading Commission (CFTC),  the federal agency that regulates commodity futures and options markets in the  United States, has witnessed an increase in the number of Internet websites  fraudulently promoting commodity trading systems and advisory services. Among  other things, these websites falsely claim that advertised performance results  are based on real trading when; in fact, the results are based on hypothetical  trading. The CFTC urges you to be skeptical when promoters of trading systems  and advisory services claim that their products and services will earn high  profits with minimal risks. You also should be forewarned that systems which  trigger frequent trading signals as part of a day trading strategy can result  in substantial commissions and fees. <br />
  <br />
  <strong>NO TRADING SYSTEM CAN GUARANTEE  PROFITS </strong><br />
  Commodity  trading systems typically are computerized programs that signal members of the  public when to buy and sell commodity futures and options contracts. Systems  produce buy and sell signals based on mathematical formulas and are typically  based on technical analysis of trading data (trading volume and prices), as  opposed to fundamental analysis (analysis of economic factors such as supply  and demand). Trading systems that are based on technical analysis attempt to  predict future price movements based on historical prices, price relationships  and price trends. In deciding whether to purchase a particular trading system  to trade commodity futures or options, members of the public should remember  that no commodity trading system can guarantee profits. And, whether or not a  trading system is used, commodity futures and options are typically high risk  endeavors. <br />
  <br />
  <strong>HYPOTHETICAL TRADING RESULTS CAN  BE UNRELIABLE </strong><br />
  Many trading  system promoters advertise their systems by reporting hypothetical trading  results. Hypothetical trading results typically are based on trading  simulations using historical price data or simulated &quot;real time&quot;  computer trading. To obtain these results, trading system promoters typically  pretend that they traded futures contracts at market prices that occurred  at&nbsp; some time in the past. They then calculate the trading results that  these purported trades would have achieved had they been placed, based on  actual historical prices. These results often show impressive trading results  and large net profits with only a few, small margin calls. Whether based on  historical data or simulated &quot;real time&quot; trading, hypothetical  results do not reflect the results of any actual trading. In other words, there  is no actual futures account, no actual investment, no actual trading, and no  actual profits. The results are purely the product of simulation. Hypothetical  trading results have several inherent limitations: </p>
<ul type="disc">
  <li>20/20 Hindsight with Historical       Results ??Since the trading systems that produced the results were not       actually traded under real market conditions, the purported results fail       to take into account market circumstances that affect traders and their       decision making process, such as anticipated news events that could have       an impact on the supply, demand or price of the commodity. </li>
  <li>&quot;Real time&quot; is not       Real When marketing trading systems, some promoters claim that their       systems have performed successfully in &quot;Real time Trading.&quot;       &quot;Real time Trading&quot; only means that the system has been tested       using a live data feed, rather than being tested using historical market       data. In &quot;Real time Trading,&quot; however, no trades have actually       been placed in the market. Performance results based on &quot;Real time       Trading&quot; are merely a form of hypothetical results, with the same       limitations. </li>
  <li>Financial Limitations.&nbsp;       Hypothetical results may not adequately take into account the ability of a       trader to absorb trading losses or to meet margin calls. Trading systems       assume that the trader can withstand all losses generated by the system       and can meet resulting margin calls. It is much easier to absorb a trading       loss on paper (hypothetically) than to do so in reality. Many traders find       it unacceptable to sustain several consecutive trading losses and/or       margin calls. Moreover, in an actual trading environment, a trader's financial condition may change over time and affect his or her       ability to continue following a trading system. </li>
  <li>Not Tested Under Real Market       Conditions Hypothetical trading results assume that futures contracts have       been bought and sold at specific prices. Since these assumptions have not       been subjected to actual market conditions, they may overestimate or       underestimate the performance of a system. In addition, some market       conditions may make it impossible to execute a trade. For instance, many       systems assume that stop loss orders will be executed at their stop price.       Under actual market conditions a stop loss order might be executed at a       better or worse price, or not be executed at all. Further, actual market       conditions include bid/ask spreads which might not be reflected in the       prices used in hypothetical trading. Moreover, the actual execution of a       trade could impact the price paid, especially in less liquid or illiquid       markets. </li>
  <li>Possible &quot;Rigging&quot; of       Results a member of the public should be alert to the possibility that the       system promoter manufactured results by selecting historical trades that       would have yielded the greatest returns. </li>
  <li>Trading and System Costs the       profit claims of promoters may fail to take into consideration the cost of       purchasing or leasing a trading system. While the prices of systems vary,       many are sold for thousands of dollars. In addition, most of these systems       require that the user obtain a data feed from a vendor. System promoters       may also fail to take into consideration the impact on profits of       commissions and fees charged by brokers in connection with futures and       options trading. Such commissions can have a substantial effect on       profitability, particularly when the system generates frequent trading       signals. A user should take all of these costs into account because they       raise the breakeven point in trading. </li>
</ul>
<p>Because of  these limitations, CFTC Regulations require that the presentation of  hypothetical trading results be accompanied by a specific cautionary statement  warning of the inherent limitations of these results. <br />
<br />
  <strong>FUTURES CONTRACTS ARE VOLATILE AND  RISKY </strong><br />
  Persons  considering trading commodity futures or options should educate themselves  about futures and options and realize that they may lose large sums of money.  Remember: &quot;If it sounds too good to be true, it probably is too good to be  true.&quot; The following checklist should help consumers in deciding whether  to use a trading system. <br />
  <br />
  <strong>IS A FUTURES/OPTIONS TRADING  SYSTEM RIGHT FOR YOU? </strong></p>
<ul type="disc">
  <li>Do you have the financial       ability to sustain trading losses and meet margin calls? When trading       futures contracts on margin, you risk losing much more money than the initial       margin amount. If the market moves against you, you may be required to pay       additional funds. The use of margin creates potentially large exposures to       loss. </li>
  <li>Can you lose your entire       investment and more without a change in your lifestyle? </li>
  <li>Do the trading results sound       too good to be true? </li>
  <li>Are the advertised trading       results based on actual trading or &quot;hypothetical&quot; trading? </li>
  <li>Has any trader used the system       in actual trading? If so, how has the trader fared? </li>
  <li>Will the system promoter       provide you with independent verification of the claimed trading results? </li>
  <li>What is the total cost of the       system? </li>
  <li>Have you factored into your       purchasing decision the impact of commissions and fees that can result       from frequent trading? </li>
  <li>What are the additional costs       (data feed, etc)? </li>
  <li>Not all system promoters are       required to be National Futures Association (NFA) members or registered       with the CFTC. A call to the NFA (800-621-3570       or 800-6764       NFA) or the CFTC, or a visit to       the NFA's website at http://www.nfa.futures.org/basicnet/, can       confirm the status of a particular promoter. </li>
  <li>Have you checked with the NFA       whether the system promoter has been disciplined by commodity regulators? </li>
</ul>
<p>Questions  concerning this advisory may be addressed to the CFTC's Office of  Public Affairs at <br />
  (202)  418-5080. <br />
  CommodityFuturesTradingCommission<br />
  ThreeLaFayetteCentre<br />
  115521stStreet,N.W.<br />
  Washington, D.C. 20581 <br />
  For other  consumer advisories concerning possible fraudulent activity in the commodity  futures and options industry, click on Consumer Alerts. The CFTC's  website also offers general information about trading in the commodity futures  and options markets. For example, the CFTC offers brochures online, such as  &quot;Futures and Options What You Should Know Before You Trade&quot; and  &quot;Glossary: The Language of the Futures Industry.&quot; To obtain this and  other information, go to the CFTC site map. he Federal Trade Commission's Advisory Day Trading Ads: Cutting Through the Bull&quot; </p>

<%--<p>The risk of trading can be substantial and each investor and/or trader must consider whether this is a suitable investment. Past performance, whether actual or indicated by simulated historical tests of strategies, is not indicative of future results. Investing through system trading is a valuable diversification tool in that it presents the opportunity for investment returns that are not correlated with other market instruments such as stock and bond markets. Balance portfolio volatility risk, enhance the investment portfolio ability to profit in any economic environment specific buy/sell decisions on a trade by trade basis. Adding managed futures or forex to stocks &amp; bonds portfolio = possible lower portfolio volatility and enhanced risk adjusted returns.</p>
<p><strong>U.S. Government Required Disclaimer -</strong> Commodity Futures Trading Commission Futures and Options trading has large potential rewards, but also large potential risk. You must be aware<br />
of the risks and be willing to accept them in order to invest in the futures and options markets. Don't trade with money you can't afford to lose. This is neither a solicitation nor an offer to Buy/Sell futures or options. No representation is being made that any account will or is likely <br />
to achieve profits or losses similar to those discussed on this web site. The past performance of any trading system or methodology is not necessarily indicative of future results.&nbsp;<br />

<br />
<strong>CFTC RULE 4.41 -</strong>Hypothetical or simulated performance results have certain limitations. Unlike an actual performance record, simulated results do not represent actual trading. &nbsp;Also, since the trades have not been executed, the results may have under-or-over compensated for the impact, if any, of certain market factors, such as lack of liquidity. &nbsp;Simulated trading programs in general are also subject to the fact that they are designed with the benefit of hindsight. &nbsp;No representation is being made that any account will or is likely to achieve profit or losses similar to those shown</font><span class="style16">.<br />
All material provided by Globex Trading Solutions is believed to be reliable. However, due to <br />
the number of sources from which we obtain information, and the inherent risks of distribution, there may be omissions or inaccuracies in such information and services.&nbsp; Globex Trading Solutions, its owners, employees, and contributors take every reasonable step to ensure the integrity of the data.&nbsp; However, Globex Trading Solutions, its owners, employees, and contributors, cannot and will not warrant the accuracy, completeness, current ness, or fitness for a particular purpose of the information contained in our products or services.<br />

Recommendations and opinions contained in our products and services reflect judgment, as applicable, of Globex Trading Solutions as of the date hereof, are subject to change, and are based upon certain assumptions that could yield different results. You are cautioned there is <br />
no universally accepted method for analyzing financial instruments, including futures.&nbsp; Further, there is no guarantee as to the liquidity of the instruments involved in its analysis.<br />
&nbsp;Neither the information nor the recommendations and opinions expressed herein constitute <br />
an offer to buy or sell any financial contracts, security, future contract, or derivative instrument.&nbsp; As a matter of policy, Globex Trading Solutions does not give tax, accounting, regulatory, or legal advice to clients.&nbsp; A client should therefore consult their own advisor regarding the tax, accounting, regulatory, or legal implications of the recommended strategies before any transactions with your account.<br />
<br />
For other consumer advisories concerning possible fraudulent activity in the commodity futures and options industry, click on <strong><a href="http://www.cftc.gov/cftc/cftccustomer.htm" target="_top">Consumer Alerts</a>.</strong> The CFTC's website also offers general information about trading in the commodity futures and options markets. For example, the CFTC offers brochures on-line, such as &quot;<strong><a href="http://www.cftc.gov/opa/brochures/opafutures.htm" target="_top">Futures and Options What You Should Know Before You Trade</a></strong>&quot; and &quot;<strong><a href="http://www.cftc.gov/opa/glossary/opaglossary_a.htm" target="new">Glossary: The Language of the Futures Industry</a></strong>.&quot; To obtain this and other information, go to the <strong><a href="http://www.cftc.gov/cftc/cftcmap.htm" target="_top">CFTC site map</a>.</strong></p>
--%>
<div style="text-align:center">
    <input type="button" name="agree" value="I agree" onclick="location='Systems2.aspx'; " />    
</div>

</asp:Content>

